/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IpcRouteImport } from './routes/ipc'
import { Route as IndexRouteImport } from './routes/index'

const IpcRoute = IpcRouteImport.update({
  id: '/ipc',
  path: '/ipc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ipc': typeof IpcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ipc': typeof IpcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ipc': typeof IpcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ipc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ipc'
  id: '__root__' | '/' | '/ipc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IpcRoute: typeof IpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ipc': {
      id: '/ipc'
      path: '/ipc'
      fullPath: '/ipc'
      preLoaderRoute: typeof IpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IpcRoute: IpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
